version: '3.8'
services:
  gateway:
    build: ./gateway

    container_name: gate
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - S_HOST=server
      - S_PORT=9090

  server:
    build: ./server

    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_NAME=shareit
      - DB_PORT=5432
      - DB_HOST=db
      - USERNAME=postgres
      - PASSWORD=test

  db:
    image: postgres:13.3
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
    volumes:
      - ./init:/docker-entrypoint-initdb.d